#!/bin/bash

args=`getopt x:v:l:sw: $*`
set -- $args

EXCLUDED_SECTIONS=""
DEFAULT_EXCLUDE_PATTERNS=("_" "[A-Z]" "[0-9]" ":")
USER_SUPPLIED_EXCLUDE_PATTERNS=()
USE_ALTERNATE_SCREEN=false
WPM=350
MAX_LENGTH=9
while true; do
    case "$1" in
        -x ) EXCLUDED_SECTIONS=$2$EXCLUDED_SECTIONS; shift 2 ;;
        -v ) USER_SUPPLIED_EXCLUDE_PATTERNS+=("$2"); shift 2 ;;
        -l ) MAX_LENGTH="$2"; shift 2 ;;
        -s ) USE_ALTERNATE_SCREEN=true; shift ;;
        -w ) WPM=$2; shift 2 ;;
        -- ) shift ; break ;;
        * ) break ;;
    esac
done

man_page_names=$(find $(manpath | tr ":" "\n") -type f -o -type l)

if [ ! $EXCLUDED_SECTIONS = "" ]; then
    man_page_names=$(echo "$man_page_names" | egrep -v "man[$EXCLUDED_SECTIONS]")
fi

man_page_names=$(echo "$man_page_names" |
    sed 's/\..*$//' |
    sed 's/.*\///' |
    egrep -v "^$" |
    uniq)

if [ ${#USER_SUPPLIED_EXCLUDE_PATTERNS[@]} -gt 0 ]; then
    exclude_patterns=( "${USER_SUPPLIED_EXCLUDE_PATTERNS[@]}" )
else
    exclude_patterns=( "${DEFAULT_EXCLUDE_PATTERNS[@]}" )
fi

for i in "${exclude_patterns[@]}"; do
    man_page_names=$(echo "$man_page_names" | egrep -v "$i")
done

# Remove man pages longer than "l" characters
if [ $MAX_LENGTH -ne -1 ]; then
    man_page_names=$(echo "$man_page_names" | egrep "^.{,$MAX_LENGTH}$")
fi

export MANWIDTH=$(tput cols)
get_random_man_page() {
    man $(echo "$man_page_names" | sort -R | head -1)
}

switch_back() {
    tput rmcup
    exit 1
}

if $USE_ALTERNATE_SCREEN; then
    tput smcup
    trap "switch_back" SIGINT
fi

while true; do
    if [ ! -n "$current_man_page" ]; then
        clear
        current_man_page=$(get_random_man_page)
    fi
    current_line=$(echo "$current_man_page" | head -1)
    current_man_page=$(echo "$current_man_page" | tail -n +2)
    echo "$current_line"
    sleep $(($(echo "$current_line" | wc -w) * 60 / $WPM))
done
