#!/bin/bash

args=`getopt x:v:l:sw: $*`
set -- $args

excluded_sections=""
default_exclude_patterns=("_" "[A-Z]" "[0-9]")
user_supplied_exclude_patterns=()
use_alternate_screen=false
wpm=350
max_length=9
while true; do
    case "$1" in
        -x ) excluded_sections=$2$excluded_sections; shift 2 ;;
        -v ) user_supplied_exclude_patterns+=("$2"); shift 2 ;;
        -l ) max_length="$2"; shift 2 ;;
        -s ) use_alternate_screen=true; shift ;;
        -w ) wpm=$2; shift 2 ;;
        -- ) shift ; break ;;
        * ) break ;;
    esac
done

man_page_names=$(find $(manpath | tr ":" "\n") -type f -o -type l)

if [ ! $excluded_sections = "" ]; then
    man_page_names=$(echo "$man_page_names" | egrep -v "man[$excluded_sections]")
fi

man_page_names=$(echo "$man_page_names" |
    sed 's/\..*$//' |
    sed 's/.*\///' |
    egrep -v "^$" |
    uniq)

if [ ${#user_supplied_exclude_patterns[@]} -gt 0 ]; then
    exclude_patterns=( "${user_supplied_exclude_patterns[@]}" )
else
    exclude_patterns=( "${default_exclude_patterns[@]}" )
fi

for i in "${exclude_patterns[@]}"; do
    man_page_names=$(echo "$man_page_names" | egrep -v "$i")
done

# Remove man pages longer than "l" characters
man_page_names=$(echo "$man_page_names" | egrep "^.{,$max_length}$")

export MANWIDTH=$(tput cols)
get_random_man_page() {
    man $(echo "$man_page_names" | sort -R | head -1)
}
current_man_page=$(get_random_man_page)

switch_back() {
    tput rmcup
    exit 1
}

if $use_alternate_screen; then
    tput smcup
    trap "switch_back" SIGINT
fi

while true; do
    current_line=$(echo "$current_man_page" | head -1)
    echo "$current_line"
    current_man_page=$(echo "$current_man_page" | tail -n +2)
    if [ ! -n "$current_man_page" ]; then
        clear
        current_man_page=$(get_random_man_page)
    fi
    sleep $(($(echo "$current_line" | wc -w) * 60 / $wpm))
done
