name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      os: [ubuntu-16.04, macOS-10.14]
    
    steps:
    - uses: actions/checkout@v1
    - name: Sucessfully outputs a random man page
      run: mansaver -o
